# ********************************************************************************************************************** #
#                                                                                                                        #
#                                                       :::    :::     :::     :::     :::   ::: ::::::::::: ::::::::::  #
#    containerdisk-centos9stream.yml                   :+:   :+:    :+: :+:   :+:     :+:   :+:     :+:     :+:          #
#                                                     +:+  +:+    +:+   +:+  +:+      +:+ +:+      +:+     +:+           #
#    By: codespace <codespace@kalyte.ro>             +#++:++    +#++:++#++: +#+       +#++:       +#+     +#++:++#       #
#                                                   +#+  +#+   +#+     +#+ +#+        +#+        +#+     +#+             #
#    Created: 2023/12/17 16:36:13 by codespace     #+#   #+#  #+#     #+# #+#        #+#        #+#     #+#              #
#    Updated: 2023/12/17 16:36:14 by codespace    ###    ### ###     ### ########## ###        ###     ##########.ro     #
#                                                                                                                        #
# ********************************************************************************************************************** #

name: Container Image CI centos9stream

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
  schedule:
  - cron: "0 0 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Github Container Registory
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Container
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and Push Container Images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./centos9stream.Dockerfile
        push: true
        tags: ghcr.io/docheio/containerdisk-centos:9-stream
        labels: ${{ steps.meta.outputs.labels }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and push to Docker Hub
      run: |
        docker pull ghcr.io/docheio/containerdisk-centos:9-stream
        docker tag  ghcr.io/docheio/containerdisk-centos:9-stream \
                    docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerdisk-centos:9-stream
        docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/containerdisk-centos:9-stream

    - name: Log in to KubevirtJP
      uses: docker/login-action@v3
      with:
        registry: kubevirt.jp
        username: ${{ secrets.KUBEVIRT_USERNAME }}
        password: ${{ secrets.KUBEVIRT_TOKEN }}

    - name: Tag and push to KubevirtJP
      run: |
        docker pull ghcr.io/docheio/containerdisk-centos:9-stream
        docker tag  ghcr.io/docheio/containerdisk-centos:9-stream \
                    kubevirt.jp/containerdisk-centos:9-stream
        docker push kubevirt.jp/containerdisk-centos:9-stream
        